### ISSUE TITLE
How to build the stuff?

### ISSUE THREAD

**Issue by techtonik** [gdamore/govisor#40]
`go get github.com/gdamore/govisor` doesn't make govisor binaries appear in GOPATH/bin directory like with proxima5. Why?

**Comment by gdamore** [comment]
I _think_ this is because govisor and govisord are in subdirectories.  If you run go get in those subdirectories, the binaries are installed.

Perhaps the source organization can/should change to make go get work better.  I'm not sure what the better way to do this would be.

**Comment by techtonik** [comment]
In LXD project the project root contains only `client.go` and `config.go`. Client gets compiled into `lxc`, client specific code goes to lxc/ server specific into lxd/ and everything else is in shared/ - https://github.com/lxc/lxd

However, it doesn't seem to produce `lxc` binary on `go get`. I don't know how this mechanism work.

**Comment by gdamore** [comment]
Added to the readme:

go get github.com/gdamore/govisor/govisor
go get github.com/gdamore/govisor/govisord
