### ISSUE TITLE
cross platform

### ISSUE THREAD

**Issue by ghost** [gdamore/govisor#52]
looking for something just like this but can run on all platforms.
Windows is currently not supported fully, but there are golang libs that provide unix commands that work on windows, so the samples can be made cross platform.
I can dig some out.

But this projects seems dead and not really supported anymore ?

**Comment by gdamore** [comment]
Its not dead, but its not super active either.  The actual framework should work fine, but the examples were never ported.

**Comment by gdamore** [comment]
#41 addresses the question about Windows examples, so there isn't any new feedback here.  Closing.  (If you want to contribute examples for Windows, I would be happy to review a PR.)
